plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${mod_id}-${minecraft_version}-${project.name}".toLowerCase()
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
}

repositories {
    mavenCentral()
    maven {
        name = 'NeoForge'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'TerraformersMC'
        url = 'https://maven.terraformersmc.com/'
    }
    maven {
        name = 'Ladysnake'
        url = 'https://maven.ladysnake.org/releases'
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : mod_name,
            'Specification-Version'   : project.jar.archiveVersion,
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : project.jar.archiveVersion,
        ])
    }
}

processResources {
    def expandProps = [
        'version': version,
        'java_version': java_version,
        'mod_id': mod_id,
        'mod_name': mod_name,
        'mod_description': mod_description,
        'minecraft_version': minecraft_version,
        'fabric_loader_version': fabric_loader_version,
        'fabric_version': fabric_version,
    ]
    filesMatching(['fabric.mod.json', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}
