# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Project
version=1.0.0
group=com.stepaument.tbhbridge

# Common
minecraft_version=26.2
java_version=25
neo_form_version=26.2-1

# Fabric
fabric_version=0.152.2+26.2
fabric_loader_version=0.19.3

# Mod Properties
mod_id=tbhbridge
mod_name=TravelersBackpackHomeostaticBridge
mod_description=Bridge between Traveler's Backpack and Homeostatic - fill your flask from your backpack!
