plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    maven {
        name = 'NeoForge'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    implementation 'net.fabricmc:fabric-loom:1.16.3'
    implementation 'net.neoforged:moddev-gradle:2.0.141'
}
